"""empty message

Revision ID: 28fa4c8c2b20
Revises: b48d73899d00
Create Date: 2023-06-25 19:17:32.921757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28fa4c8c2b20'
down_revision = 'b48d73899d00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
