"""empty message

Revision ID: 293ca48ebb2d
Revises: d5db4ffda770
Create Date: 2023-06-25 19:11:15.387387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '293ca48ebb2d'
down_revision = 'd5db4ffda770'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
