"""empty message

Revision ID: a7398b6429bc
Revises: c6f48be69d8a
Create Date: 2023-06-25 19:05:17.581883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7398b6429bc'
down_revision = 'c6f48be69d8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
