"""empty message

Revision ID: b48d73899d00
Revises: f3317912c3c5
Create Date: 2023-06-25 19:17:01.819805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b48d73899d00'
down_revision = 'f3317912c3c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
