"""empty message

Revision ID: c6f48be69d8a
Revises: 7f88d5f08c15
Create Date: 2023-06-14 15:54:25.897340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6f48be69d8a'
down_revision = '7f88d5f08c15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('districts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('records', sa.Column('district_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'records', 'districts', ['district_id'], ['id'], ondelete='CASCADE')
    op.drop_column('records', 'district')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('district', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'records', type_='foreignkey')
    op.drop_column('records', 'district_id')
    op.drop_table('districts')
    # ### end Alembic commands ###
