"""empty message

Revision ID: d5db4ffda770
Revises: a7398b6429bc
Create Date: 2023-06-25 19:10:38.113263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5db4ffda770'
down_revision = 'a7398b6429bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
