"""empty message

Revision ID: f3317912c3c5
Revises: 293ca48ebb2d
Create Date: 2023-06-25 19:16:09.145125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3317912c3c5'
down_revision = '293ca48ebb2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
